### Your Name Here: Philip Karpowich
### Your TF Name: Kaleigh
### Graduate or Undergraduate Credit: Graduate

In [109]:
import numpy as np
import pandas as pd 


In [110]:
# import website.csv into a dataframe called whiteWine. 
path = "C:\\Users\\ptkar\\Desktop\\Python Data Science\\website.csv"
df = pd.read_csv(path, sep=",")

df.head()

URL  URL_LENGTH  NUMBER_SPECIAL_CHARACTERS     CHARSET  \
0   M0_109          16                          7  iso-8859-1   
1  B0_2314          16                          6       UTF-8   
2   B0_911          16                          6    us-ascii   
3   B0_113          17                          6  ISO-8859-1   
4   B0_403          17                          6       UTF-8   

                  SERVER  CONTENT_LENGTH WHOIS_COUNTRY WHOIS_STATEPRO  \
0                  nginx           263.0          None           None   
1          Apache/2.4.10         15087.0          None           None   
2  Microsoft-HTTPAPI/2.0           324.0          None           None   
3                  nginx           162.0            US             AK   
4                   None        124140.0            US             TX   

      WHOIS_REGDATE WHOIS_UPDATED_DATE  ...   DIST_REMOTE_TCP_PORT  \
0  10/10/2015 18:21               None  ...                      0   
1              None               None  ...                      7   
2              None               None  ...                      0   
3    7/10/1997 4:00     12/9/2013 0:45  ...                     22   
4    12/5/1996 0:00     11/4/2017 0:00  ...                      2   

   REMOTE_IPS  APP_BYTES  SOURCE_APP_PACKETS  REMOTE_APP_PACKETS  \
0           2        700                   9                  10   
1           4       1230                  17                  19   
2           0          0                   0                   0   
3           3       3812                  39                  37   
4           5       4278                  61                  62   

   SOURCE_APP_BYTES  REMOTE_APP_BYTES  APP_PACKETS  DNS_QUERY_TIMES  Type  
0              1153               832            9              2.0     1  
1              1265              1230           17              0.0     0  
2                 0                 0            0              0.0     0  
3             18784              4380           39              8.0     0  
4            129889              4586           61              4.0     0  

[5 rows x 21 columns]

In [111]:
# Turn Charset and Server features into dummy variables

dummy_features_gen = pd.get_dummies(df['CHARSET'], drop_first=False)

df = pd.concat([df,dummy_features_gen], axis =1 )
df = df.drop('CHARSET', axis = 1)

dummy_features_gen = pd.get_dummies(df['SERVER'], drop_first=False)
df = pd.concat([df,dummy_features_gen], axis =1 )
df = df.drop('SERVER', axis = 1)



# removing url 
df = df.drop('URL', axis = 1)


In [112]:
# turning 'None' values into 01/01/1990
type(df['WHOIS_REGDATE'][0])

df['WHOIS_REGDATE'] = df['WHOIS_REGDATE'].apply(lambda x: '01/01/1900 0:00' if x == 'None' else x )
df['WHOIS_UPDATED_DATE'] = df['WHOIS_UPDATED_DATE'].apply(lambda x: '01/01/1900 0:00' if x == 'None' else x )

# syntex for splitting stings on a DF came from https://stackoverflow.com/questions/14745022/how-to-split-a-column-into-two-columns
# purpose of this is to get rid of the time field as I am looking to see many days we currently am from this date.
# for furthur analysis, it might be worth binning the times into morning/afternoon/night.

df['WHOIS_REGDATE'] = df['WHOIS_REGDATE'].str.split(' ',1,expand=True)[0]
df['WHOIS_UPDATED_DATE'] = df['WHOIS_UPDATED_DATE'].str.split(' ',1,expand=True)[0]



In [114]:
# changing the Whois_country and whois_StateProd into binary variables
df['WHOIS_COUNTRY'] = df['WHOIS_COUNTRY'].apply(lambda x: 0 if x == 'None' else 1 )
df['WHOIS_STATEPRO'] = df['WHOIS_STATEPRO'].apply(lambda x: 0 if x == 'None' else 1 )

In [115]:
# Turning NaN values to 0
df['CONTENT_LENGTH'] = np.nan_to_num(df['CONTENT_LENGTH'])

df['DNS_QUERY_TIMES'] = np.nan_to_num(df['DNS_QUERY_TIMES'])



In [118]:
# Droping whois_regdate and whois_updated_Date due to formatting issues. Would like to re-visit though if time permits.
df = df.drop('WHOIS_REGDATE', axis = 1)
df = df.drop('WHOIS_UPDATED_DATE', axis = 1)

In [190]:
# split the dataset into two for each class. This will be used only for exploritary data analysis and not for the modeling.

df_0 = df.loc[df["Type"] == 0]
df_1 = df.loc[df["Type"] == 1]

display(df_0.head())
display(df_1.head())


URL_LENGTH  NUMBER_SPECIAL_CHARACTERS  CONTENT_LENGTH  WHOIS_COUNTRY  \
1          16                          6         15087.0              0   
2          16                          6           324.0              0   
3          17                          6           162.0              1   
4          17                          6        124140.0              1   
5          18                          7             0.0              1   

   WHOIS_STATEPRO  TCP_CONVERSATION_EXCHANGE  DIST_REMOTE_TCP_PORT  \
1               0                         17                     7   
2               0                          0                     0   
3               1                         31                    22   
4               1                         57                     2   
5               1                         11                     6   

   REMOTE_IPS  APP_BYTES  SOURCE_APP_PACKETS            ...             \
1           4       1230                  17            ...              
2           0          0                   0            ...              
3           3       3812                  39            ...              
4           5       4278                  61            ...              
5           9        894                  11            ...              

   nginx/1.8.0  nginx/1.8.1  nginx/1.9.13  nxfps  openresty  \
1            0            0             0      0          0   
2            0            0             0      0          0   
3            0            0             0      0          0   
4            0            0             0      0          0   
5            0            0             0      0          0   

   openresty/1.11.2.1  openresty/1.11.2.2  squid/3.3.8  tsa_c  \
1                   0                   0            0      0   
2                   0                   0            0      0   
3                   0                   0            0      0   
4                   0                   0            0      0   
5                   0                   0            0      0   

   www.lexisnexis.com  9999  
1                         0  
2                         0  
3                         0  
4                         0  
5                         0  

[5 rows x 264 columns]

URL_LENGTH  NUMBER_SPECIAL_CHARACTERS  CONTENT_LENGTH  WHOIS_COUNTRY  \
0           16                          7           263.0              0   
8           20                          5             0.0              0   
9           20                          5             0.0              0   
15          21                          7           957.0              1   
16          21                          7           686.0              1   

    WHOIS_STATEPRO  TCP_CONVERSATION_EXCHANGE  DIST_REMOTE_TCP_PORT  \
0                0                          7                     0   
8                0                          0                     0   
9                0                          0                     0   
15               0                          7                     0   
16               1                          6                     0   

    REMOTE_IPS  APP_BYTES  SOURCE_APP_PACKETS            ...             \
0            2        700                   9            ...              
8            0          0                   2            ...              
9            0          0                   2            ...              
15           1        717                  11            ...              
16           2        603                   8            ...              

    nginx/1.8.0  nginx/1.8.1  nginx/1.9.13  nxfps  openresty  \
0             0            0             0      0          0   
8             0            0             0      0          0   
9             0            0             0      0          0   
15            0            0             0      0          0   
16            0            0             0      0          0   

    openresty/1.11.2.1  openresty/1.11.2.2  squid/3.3.8  tsa_c  \
0                    0                   0            0      0   
8                    0                   0            0      0   
9                    0                   0            0      0   
15                   0                   0            0      0   
16                   0                   0            0      0   

    www.lexisnexis.com  9999  
0                          0  
8                          0  
9                          0  
15                         0  
16                         0  

[5 rows x 264 columns]

In [132]:
display(df_0.iloc[:,0:15].describe())
display(df_1.iloc[:,0:15].describe())

URL_LENGTH  NUMBER_SPECIAL_CHARACTERS  CONTENT_LENGTH  WHOIS_COUNTRY  \
count  1564.000000                1564.000000     1564.000000    1564.000000   
mean     55.319693                  10.638747     7084.894501       0.845908   
std      24.517587                   4.027806    29203.422125       0.361152   
min      16.000000                   6.000000        0.000000       0.000000   
25%      39.000000                   8.000000        0.000000       1.000000   
50%      50.000000                  10.000000      229.500000       1.000000   
75%      66.000000                  12.000000     4834.500000       1.000000   
max     249.000000                  43.000000   649263.000000       1.000000   

       WHOIS_STATEPRO  TCP_CONVERSATION_EXCHANGE  DIST_REMOTE_TCP_PORT  \
count     1564.000000                1564.000000           1564.000000   
mean         0.814578                  16.876598              6.148338   
std          0.388764                  42.660627             23.180777   
min          0.000000                   0.000000              0.000000   
25%          1.000000                   0.000000              0.000000   
50%          1.000000                   7.000000              1.000000   
75%          1.000000                  23.000000              6.000000   
max          1.000000                1194.000000            708.000000   

        REMOTE_IPS     APP_BYTES  SOURCE_APP_PACKETS  REMOTE_APP_PACKETS  \
count  1564.000000  1.564000e+03         1564.000000         1564.000000   
mean      3.161765  3.218852e+03           19.084399           19.325448   
std       3.497012  5.980743e+04           43.755785           48.994205   
min       0.000000  0.000000e+00            0.000000            0.000000   
25%       0.000000  0.000000e+00            0.000000            0.000000   
50%       2.000000  6.340000e+02            8.000000            8.000000   
75%       5.000000  2.402250e+03           27.000000           25.000000   
max      17.000000  2.362906e+06         1198.000000         1284.000000   

       SOURCE_APP_BYTES  REMOTE_APP_BYTES  APP_PACKETS  DNS_QUERY_TIMES  
count      1.564000e+03      1.564000e+03  1564.000000      1564.000000  
mean       1.704126e+04      3.386857e+03    19.084399         2.188619  
std        7.399947e+04      5.981022e+04    43.755785         2.922036  
min        0.000000e+00      0.000000e+00     0.000000         0.000000  
25%        0.000000e+00      0.000000e+00     0.000000         0.000000  
50%        5.620000e+02      6.720000e+02     8.000000         0.000000  
75%        1.157975e+04      2.741250e+03    27.000000         4.000000  
max        2.060012e+06      2.362906e+06  1198.000000        14.000000

URL_LENGTH  NUMBER_SPECIAL_CHARACTERS  CONTENT_LENGTH  WHOIS_COUNTRY  \
count  216.000000                 216.000000      216.000000     216.000000   
mean    68.981481                  14.550926     1127.694444       0.699074   
std     41.806416                   6.316254     3010.439121       0.459726   
min     16.000000                   5.000000        0.000000       0.000000   
25%     37.000000                  10.000000        0.000000       0.000000   
50%     49.000000                  12.000000        0.000000       1.000000   
75%    100.000000                  20.000000      652.000000       1.000000   
max    198.000000                  36.000000    27103.000000       1.000000   

       WHOIS_STATEPRO  TCP_CONVERSATION_EXCHANGE  DIST_REMOTE_TCP_PORT  \
count      216.000000                 216.000000            216.000000   
mean         0.666667                  11.879630              0.606481   
std          0.472500                  18.073863              1.882046   
min          0.000000                   0.000000              0.000000   
25%          0.000000                   0.000000              0.000000   
50%          1.000000                   8.000000              0.000000   
75%          1.000000                  18.000000              1.000000   
max          1.000000                 208.000000             18.000000   

       REMOTE_IPS     APP_BYTES  SOURCE_APP_PACKETS  REMOTE_APP_PACKETS  \
count  216.000000    216.000000          216.000000          216.000000   
mean     2.342593   1283.615741           14.685185           14.638889   
std      2.331431   1814.021798           20.223702           18.744033   
min      0.000000      0.000000            0.000000            1.000000   
25%      0.000000      0.000000            0.000000            3.000000   
50%      2.000000    810.000000           11.000000           10.000000   
75%      4.000000   2185.000000           24.000000           21.250000   
max     10.000000  20074.000000          228.000000          216.000000   

       SOURCE_APP_BYTES  REMOTE_APP_BYTES  APP_PACKETS  DNS_QUERY_TIMES  
count        216.000000        216.000000   216.000000       216.000000  
mean        7648.611111       1495.726852    14.685185         2.805556  
std        22799.897909       1997.082168    20.223702         2.944315  
min           62.000000          0.000000     0.000000         0.000000  
25%          186.000000          0.000000     0.000000         0.000000  
50%         1179.500000       1002.500000    11.000000         2.000000  
75%         3789.750000       2605.500000    24.000000         6.000000  
max       270752.000000      21646.000000   228.000000        20.000000

Couple of noticable data points are shown with the exploritory data above. 

1) CONTENT_LENGTH is markedly higher in non-mallicious websites than mallisious websites
2) There are a higher percentage of non-malliscous which have a WHOIS_COUNTRY and WHOIS_STATEPRO than mallicious websites
3) Is there website has a value for APP_BYTES, it appears to have a lower chance of being mallicious. Same with App Packets

In [145]:
target = df['Type']
features = df.drop('type', axis = 1)

#only using the first 15 features to start with
features = features.iloc[:,0:15]

In [209]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier


In [181]:
#Naive Bayes

clf = GaussianNB()
clf.fit(featureTrain, targetTrain)
predictions =  clf.predict(featureTest)
print(clf.score(featureTest, targetTest))

0.395131086142


In [183]:
confusion_matrix(targetTest, predictions)

array([[161, 320],
       [  3,  50]], dtype=int64)

The fact that the data is so skewed makes sense that naive bayes does not work very well. The model will by default pick 0 as an outcome as their are so many more 0 records.

In [208]:
# logistic regression
clf = LogisticRegression(solver = 'newton-cg', max_iter = 10090)
clf.fit(featureTrain, targetTrain)
predictions =  clf.predict(featureTest)
print(clf.score(featureTest, targetTest))

display(confusion_matrix(targetTest, predictions))

0.928838951311


C:\Users\ptkar\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:285: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\Users\ptkar\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')


array([[468,  13],
       [ 25,  28]], dtype=int64)

In [227]:
# KNN

knn = KNeighborsClassifier(n_neighbors=50, n_jobs = -1)
knn.fit(featureTrain, targetTrain)
predictions =  knn.predict(featureTest)
print(knn.score(featureTest, targetTest))


display(confusion_matrix(targetTest, predictions))

0.938202247191


array([[480,   1],
       [ 32,  21]], dtype=int64)

In [217]:
# Random Forest
clf = RandomForestClassifier( n_estimators=10000, n_jobs = -1, criterion= 'entropy', random_state = 0)
clf.fit(featureTrain, targetTrain)


predictions = clf.predict(featureTest)
print(clf.score(featureTest, targetTest))

display(confusion_matrix(targetTest, predictions))

0.97191011236


array([[475,   6],
       [  9,  44]], dtype=int64)

In [219]:
# re-doing the random forest with all variable instead of only the first 15.

# remaking the features df with all features from the origional df
features = df.drop('type', axis = 1)

featureTrain, featureTest, targetTrain, targetTest = train_test_split(features, target, test_size = 0.3, random_state = 0)

clf = RandomForestClassifier( n_estimators=10000, n_jobs = -1, criterion= 'entropy')
clf.fit(featureTrain, targetTrain)


predictions = clf.predict(featureTest)
print(clf.score(featureTest, targetTest))

display(confusion_matrix(targetTest, predictions))

1.0


array([[481,   0],
       [  0,  53]], dtype=int64)

So by adding all of my variables back into the model, I got a perfect score for the random forest model above. I am curious to see if other models might improve as well.

In [228]:
#Logistic Regression again!

clf = LogisticRegression(solver = 'newton-cg', max_iter = 10090)
clf.fit(featureTrain, targetTrain)
predictions =  clf.predict(featureTest)
print(clf.score(featureTest, targetTest))

display(confusion_matrix(targetTest, predictions))

1.0


array([[481,   0],
       [  0,  53]], dtype=int64)

In [229]:
# KNN

knn = KNeighborsClassifier(n_neighbors=50, n_jobs = -1)
knn.fit(featureTrain, targetTrain)
predictions =  knn.predict(featureTest)
print(knn.score(featureTest, targetTest))

display(confusion_matrix(targetTest, predictions))

0.938202247191


array([[480,   1],
       [ 32,  21]], dtype=int64)

It is very interesting that logistic regression improves dramatically based on the additional variables but KNN does not.